var tables = [
  {
    "author": "Graham Siggins",
    "authorSs": "sigalig",
    "elements": {"e":"DF,UF", "w":"DFr,UFr", "x":"Ubl", "t":"Ul", "c":"UBL,UFr"},
    "preview": ["gra0","gra1","gra2","gra3","gra4","gra5"],
    "url": "https://docs.google.com/spreadsheets/d/1-AnKGJMHN3SAOcZxem3XJ5tBm7Dk1dTRcZ7KcXYbGP4/",
    "mirrors": {"vk":"https://vk.com/doc-148424355_467378519", "ru":"Grahams comms.xlsx", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"},
  },
  {
    "author": "Elliot Kobelansky",
    "authorSs": "",
    "elements": {"e": "UF, UB, UR, UL, DF, DB, FR, FL, DR, DL", "c": "UFR, UBR, UFL, UBL, RDF, RDB", "Parity": "3BLD", "2-flip e": "all"},
    "preview": ["ell1", "ell2", "ell3", "ell4"],
    "url": "https://docs.google.com/spreadsheets/d/1txRjB-fAWWSM-1e1w-eJbDp9xhu0ZDwLWQdswNZhcew/edit?usp=drivesdk",
    "mirrors": {"vk":"", "yd":""},
  },
  {
    "author": "Max Hilliard",
    "authorSs": "",
    "elements": {"e": "UF, UB, UR, UL, DF, DB, FR, FL, DR, DL", "c": "UFR, UBR, UFL, UBL, RDF, RDB", "2-twists c": "all", "2-flip e": "all"},
    "preview": ["hil1", "hil2", "hil3", "hil4"],
    "url": "https://docs.google.com/spreadsheets/d/1yq-2rgkTZFu5REdasRke0YPusuTBb5J-EscChFf42Fc/edit?usp=sharing",
    "mirrors": {"vk":"https://vk.com/doc-148424355_573979140", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"},
  },
  {
    "author": "Tom Nelson",
    "authorSs": "CyanSandwich",
    "elements": {"w":"UFr", "x":"Ubr", "t":"Uf"},
    "preview": ["tom1", "tom2", "tom3"],
    "url": "https://docs.google.com/spreadsheets/d/1v5rXOH7MUxtuTEzxX6MJYe1XJMhJpZttwGpeg3nuIZo",
    "mirrors": {"vk":"https://vk.com/doc-148424355_446681725", "ru":"Tom Comms.xlsx", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"},
  },
  {
    "author": "Daniel Lin",
    "authorSs": "Daniel Lin",
    "elements": {"e":"UF", "w":"UFr", "x":"Ufr", "t":"Uf", "c":"UFR"},
    "preview": ["lin1", "lin2", "lin3", "lin4", "lin5", "lin6"],
    "url": "https://docs.google.com/spreadsheets/d/1yHyLJDvVbuEsoHONefUq7jAAFta9qM9wydwfSrJOZWQ/",
    "mirrors": {"vk":"https://vk.com/doc-148424355_446681580", "ru":"Daniel algs.xlsx", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"},
  },
  {
    "author": "Ishaan Agrawal",
    "authorSs": "fp4316",
    "elements": {"e":"UF, DF", "c":"UBL"},
    "preview": ["ish0", "ish1", "ish2", "ish3", "ish4"],
    "url": "https://docs.google.com/spreadsheets/d/1_jbYWfHAPnuICeSD2HtkJSHHbYHspilRsb097Fo08WA",
    "mirrors": {"vk":"https://vk.com/doc-148424355_465204132", "ru":"Ishaan.xlsx", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"},
  },
  {
    "author": "Sukant Koul",
    "authorSs": "arquillian",
    "elements": {"c":"UBL", "e": "FU, DF", "x": "Ubl", "w": "DFr, FUr", "t": "Ub"},
    "preview": ["fritz1", "fritz2", "fritz3"],
    "url": "https://docs.google.com/spreadsheets/d/1iA5-_I6p-w_bCThRTwzfTJ3RUtHFQBEd7LT1ryp9tYQ/edit#gid=1416785101",
    "mirrors": {"yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"},
  },
  {
    "author": "Jack Cai",
    "authorSs": "",
    "elements": {"c":"URF", "e":"UF"},
    "preview": ["jack2021-1", "jack2021-2", "jack2021-3"],
    "url": "https://docs.google.com/spreadsheets/d/1jBX99yDLKUHbO_MvQ44IvKG921Yy1J4TcJxQ4rJkTRU/edit",
    "mirrors": {"vk":"", "ru":"", "yd":""}
  },
    /* good tables end here */

  {
    "author": "Roman Strakhov",
    "authorSs": "Roman",
    "elements": {"e": "UF", "w": "UFl", "x": "Ubr", "t": "Uf", "c": "UBR"},
    "preview": ["roman1", "roman2", "roman3", "roman4", "roman5", "roman6"],
    "url": "https://docs.google.com/spreadsheets/d/19OfVecQfJtl_KI2vDFBP-mOCSiowUizXzoKwl3wlmD4",
    "mirrors": {"vk":"https://vk.com/doc-148424355_446681706", "ru":"Roman algs list.xlsx", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"}
  },
  {
    "author": "Stanley Chapel",
    "authorSs": "schapel",
    "elements": {"4BLD parity":"w"},
    "preview": ["stan1", "stan2"],
    "url": "https://docs.google.com/spreadsheets/d/1kT9Pua3nlvTayguES2HYFi1Fgb-AQrLF1k9hZNjEU_8/edit",
    "mirrors": {"yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"},
  },
  {
    "author": "Roman Strakhov",
    "authorSs": "Roman",
    "elements": {"w": "all of: UFl, DFr, UBr, URf"},
    "preview": ["wingsgen0", "wingsgen1", "wingsgen2", "wingsgen3"],
    "url": "https://docs.google.com/spreadsheets/d/1c_thx0i5__sJkZk8BN5LKbxxZVpp5abkla1OQddWQpg",
    "mirrors": {"vk":"https://vk.com/doc-148424355_452766991", "ru":"wings 3cycles generated.xlsx", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"}
  },
  {
    "author": "Roman Strakhov",
    "authorSs": "Roman",
    "elements": {"x": "all of: Urb, Ubl, Ulf, Ufr"},
    "preview": ["xgen0", "xgen1", "xgen2"],
    "url": "https://docs.google.com/spreadsheets/d/1AklynqvWVFkO0C24P_n72XJUD2Pgd27iooQF3xf9dYQ",
    "mirrors": {"vk":"https://vk.com/doc-148424355_452767013", "ru":"x-centers 3cycles generated.xlsx", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"}
  },
  {
    "author": "Mark Rivers",
    "authorSs": "mark49152",
    "elements": {"e":"DF", "w":"DFr"},
    "preview": ["mrivers1","mrivers2","mrivers3","mrivers4"],
    "url": "https://docs.google.com/spreadsheets/d/1vrvZmSdph7shZ51gMt5qTwtdcjkVAL8fWEUFAyK3HbI/edit?usp=sharing",
    "mirrors": {"yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"},
  },
  {
    "author": "Linus Fresz",
    "authorSs": "mycube",
    "elements": {"e":"DF", "w":"DFr", "x":"Ubl", "t":"Df","c":"UBL"},
    "preview": ["linus1", "linus2", "linus3", "linus4", "linus5"],
    "url": "https://docs.google.com/spreadsheets/d/1PN48uEuTh1IHfs3IsmiCHfOLkBTd9eYMn8OX2vPoMeI/",
    "mirrors": {"vk":"https://vk.com/doc-148424355_446681642", "ru":"Linus algs.xlsx", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"},
  },
  {
    "author": "Oliver Frost",
    "authorSs": "Ollie",
    "elements": {"e":"DF", "w":"DFr", "x":"Ubl", "t":"Ub"},
    "preview": ["ollie1", "ollie2", "ollie3", "ollie4"],
    "url": "https://docs.google.com/spreadsheets/d/15e0ts12QHKHb9Or6BvO6hlXfns2hJgZoXCGpsIR0YGc",
    "mirrors": {"vk":"https://vk.com/doc-148424355_446681669", "ru":"Ollie algs.xlsx", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"},
  },
  {
    "author": "Deni Mintsaev",
    "authorSs": "denthebro",
    "elements": {"e":"UF", "c":"UFR,UBL"},
    "preview": ["deni0","deni1","deni2","deni3"],
    "url": "",
    "mirrors": {"vk":"https://vk.com/doc-148424355_469342228", "ru":"Deni.xlsx", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"},
  },
  {
    "author": "Diego Meneghetti",
    "authorSs": "Meneghetti",
    "elements": {"e":"DF", "x":"Ubr", "c":"UBL"},
    "preview": ["mene1", "mene2", "mene3", "mene4", "mene5"],
    "url": "https://docs.google.com/spreadsheets/d/1hXi9B9lCubA9Ur_31VmYleiLUnWuUUIWf4aTPQkj0bg/edit",
    "mirrors": {"vk":"https://vk.com/doc-148424355_446681657", "ru":"Meneghetti 3-Style.xlsx", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"},
  },
  {
    "author": "Daniel White",
    "authorSs": "DeeDub",
    "elements": {"e":"UF", "c":"UBL"},
    "preview": ["deedub1", "deedub2"],
    "url": "https://docs.google.com/spreadsheets/d/1q3z9dEtl6sem1ZXGJue_w_0BHf-obhY8bg2Oo_oNbq8/",
    "mirrors": {"vk":"https://vk.com/doc-148424355_446681601", "ru":"DeeDubb Commutators.xlsx", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"},
  },
  {
    "author": "Oleg Gritsenko",
    "authorSs": "drkorbin",
    "elements": {"e":"UF", "w":"UFl"},
    "preview": ["oleg1", "oleg2"],
    "url": "https://docs.google.com/spreadsheets/d/1hwmqw6ry2tEAVcXrUbMDevr6doBzkQmcZrxG8DA7BPQ",
    "mirrors": {"vk":"https://vk.com/doc-148424355_446681663", "ru":"Oleg edges and wings.xlsx", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"},
  },
  {
    "author": "Sebastiano Tronto",
    "authorSs": "porkydays",
    "elements": {"e":"UR", "c":"UBL"},
    "preview": ["porky1", "porky2"],
    "url": "https://docs.google.com/spreadsheets/d/17sL1RuiYijTMiQkBn_d5xthdgAoxGE8oaH-Po-PZ58s",
    "mirrors": {"vk":"https://vk.com/doc-148424355_446681689", "ru":"Porky comms.xlsx", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"},
  },
  {
    "author": "Oliver Fritz",
    "authorSs": "Olli Fritz",
    "elements": {"c":"UFR", "e": "UF", "x": "Ubr", "w": "UFr", "t": "Ur"},
    "preview": ["fritz1", "fritz2", "fritz3"],
    "url": "https://docs.google.com/spreadsheets/d/19BTxDEpkJSQeyWZ58PVcCKjVG8wcP8oJZcnYSnYGyeY/",
    "mirrors": {"yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"},
  },
  {
    "author": "Grzegorz Pacewicz",
    "authorSs": "h2f",
    "elements": {"e":"DF", "c":"UBL"},
    "preview": ["h2f1", "h2f2", "h2f3", "h2f4"],
    "url": "https://docs.google.com/spreadsheets/d/1rnyEbUmmD18tKdFnYChF2LBSyykfOrfX9CGiJOb-LZM",
    "mirrors": {"vk":"https://vk.com/doc-148424355_446681613", "ru":"h2f algs.xlsx", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"},
  },
  {
    "author": "Oleg Gritsenko",
    "authorSs": "drkorbin",
    "elements": {"x":"Ubr"},
    "preview": ["oleg_x"],
    "url": "https://docs.google.com/spreadsheets/d/1mtgwTouNmIGZr9bJIPx8E7LBSmvQ6oLuOxbqTlBg0ac",
    "mirrors": {"vk":"https://vk.com/doc-148424355_446682303", "ru":"Oleg x-centers.xlsx", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"},
  },
  {
    "author": "James Molloy",
    "authorSs": "Mollerz",
    "elements": {"e":"DF", "w":"DFr", "x":"Ubl", "t":"Ub", "c":"UBL"},
    "preview": ["moll1","moll2","moll3","moll4","moll5"],
    "url": "https://docs.google.com/spreadsheets/d/1JsrKCRw5V7gE6Np6iRog804lrKEiUzfv_Eaaulq-PWc",
    "mirrors": {"vk":"https://vk.com/doc-148424355_461769267", "ru":"mollerz.xlsx", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"},
  },
  {
    "author": "Grzegorz Jałocha",
    "authorSs": "sneze2r",
    "elements": {"c":"UBR"},
    "preview": ["grzegorz1"],
    "url": "https://docs.google.com/spreadsheets/d/1mkT-9vlN2H6jqzOYlUpAwj1S_mumnABOgVUkLTyoufk/edit#gid=6",
    "mirrors": {"vk":"https://vk.com/doc-148424355_446681608", "ru":"GJ Corners UBR.xlsx", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"},
  },
  {
    "author": "Grzegorz Jałocha",
    "authorSs": "sneze2r",
    "elements": {"e":"UF"},
    "preview": ["gj_e1", "gj_e2", "gj_e3"],
    "url": "https://docs.google.com/spreadsheets/d/17OF4aupkuwaAVQcRtwsREgqY2VPv-hjOxPuL4S6Y6D8/pubhtml#",
    "mirrors": {"vk":"https://vk.com/doc-148424355_447476859", "ru":"GJ UF edges.xlsx", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"},
  },
  {
    "author": "Marcell Endrey",
    "authorSs": "Marcell",
    "elements": {"e":"DF", "w":"DFr", "x":"Ufl", "t":"Uf", "c":"DRF"},
    "preview": ["marcell0", "marcell1", "marcell2", "marcell3", "marcell4", "marcell5"],
    "url": "https://docs.google.com/spreadsheets/d/11p37_js6wB0LmzPEQvKG9XqBrH8IC_piFdbejmvUH-c/",
    "mirrors": {"vk":"https://vk.com/doc-148424355_446642774", "ru":"Marcell BLD alg sheet.xlsx", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"},
  },
  {
    "author": "Arrik Aragorn Leman",
    "authorSs": "A Leman",
    "elements": {"e":"UF"},
    "preview": ["aleman1", "aleman2"],
    "url": "https://www.speedsolving.com/forum/threads/a-lemans-3style-edge-algs.38382/",
    "mirrors": {"vk":"https://vk.com/doc-148424355_447477163", "ru":"ALeman edges.txt", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"},
  },
  {
    "author": "带人过球",
    "authorSs": "",
    "elements": {"e":"DF"},
    "preview": ["df440-1", "df440-2"],
    "url": "http://bbs.mf8-china.com/forum.php?mod=viewthread&tid=95772",
    "mirrors": {},
  },
  {
    "author": "Aron Puddy-Mathew",
    "authorSs": "aronpm",
    "elements": {"e":"DF"},
    "preview": ["aaron1"],
    "url": "http://aronpm.cubing.net/algs/df.txt",
    "mirrors": {"vk":"https://vk.com/doc-148424355_446681538", "ru":"AaronPM DF edges.txt", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"},
  },
  {
    "author": "Noah Arthurs",
    "authorSs": "Noahaha",
    "elements": {"c":"UBL"},
    "preview": ["noah1", "noah2"],
    "url": "https://www.speedsolving.com/forum/threads/noahs-3-style-algs.40042/",
    "mirrors": {"vk":"https://vk.com/doc-148424355_446681661", "ru":"Noah.txt", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"},
  },
  {
    "author": "Jayden McNeill",
    "authorSs": "ottozing",
    "elements": {"c":"UBL"},
    "preview": ["jay2", "jay1"],
    "url": "https://www.speedsolving.com/forum/threads/yet-another-3style-corners-list-jay-mcneill-meh-tier-bld-solver.56714/",
    "mirrors": {"vk":"https://vk.com/doc-148424355_446681629", "ru":"jay.txt", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"},
  },
  {
    "author": "Rob Holt",
    "authorSs": "riffz",
    "elements": {"e":"DF"},
    "preview": ["riffz1", "riffz2"],
    "url": "https://docs.google.com/spreadsheets/d/1awrL4JJogL_f6R3SqbneCw4LVyNhMy5JRWJUTAzCS7I",
    "mirrors": {"vk":"https://vk.com/doc-148424355_446681695", "ru":"Riffz 3x3 BLD Edge Algs.xlsx", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"},
  },
  {
    "author": "Oliver Frost",
    "authorSs": "Ollie",
    "elements": {"w":"DFr"},
    "preview": ["ollie_w1", "ollie_w2"],
    "url": "https://docs.google.com/spreadsheets/d/1t27cXMVJoyOE2CNvT8Tt9V5k2XWTLSz4jhT1QL0xfx4",
    "mirrors": {"vk":"https://vk.com/doc-148424355_446681678", "ru":"Ollie DFr buffer wing commutators.xlsx", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"},
  },
  {
    "author": "Daniel Beyer and Chris Hardwick",
    "authorSs": "cmhardw",
    "elements": {"e":"UR"},
    "preview": ["bh_edge1", "bh_edge2"],
    "url": "http://www.speedcubing.com/chris/bhedges.html",
    "mirrors": {"vk":"https://vk.com/doc-148424355_446681561", "ru":"Beyer-Hardwick Edge Algorithms.pdf", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"},
  },
  {
    "author": "Daniel Beyer and Chris Hardwick",
    "authorSs": "cmhardw",
    "elements": {"c":"UBR"},
    "preview": ["bh_corners1", "bh_corners2", "bh_corners3"],
    "url": "http://www.speedcubing.com/chris/bhcorners.html",
    "mirrors": {"vk":"https://vk.com/doc-148424355_446681555", "ru":"Beyer-Hardwick Corner Algorithms.pdf", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"},
  },
  {
    "author": "Lucas Rolando",
    "authorSs": "lucarubik",
    "elements": {"e":"UB"},
    "preview": ["lucar_e1", "lucar_e2"],
    "url": "https://www.speedsolving.com/forum/threads/the-edge-cycles-i-use-for-bld.36014/",
    "mirrors": {"vk":"https://vk.com/doc-148424355_446681650", "ru":"lucasedges.txt", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"},
  },
  {
    "author": "Lucas Rolando",
    "authorSs": "lucarubik",
    "elements": {"c":"UBL"},
    "preview": ["lucar_c1", "lucar_c2"],
    "url": "https://www.speedsolving.com/forum/threads/the-corner-cycles-i-use-for-bld.36145/",
    "mirrors": {"vk":"https://vk.com/doc-148424355_446681647", "ru":"lucascorners.txt", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"},
  },
  {
    "author": "Xin Shi",
    "authorSs": "",
    "elements": {"c":"UFR"},
    "preview": ["xinc1", "xinc2"],
    "url": "",
    "mirrors": {"vk":"https://vk.com/doc-148424355_446681971", "ru":"Xin/Xin corners.xls", "yd":"https://yadi.sk/d/JA-HcD833JzMBh"},
  },
  {
    "author": "Xin Shi",
    "authorSs": "",
    "elements": {"e":"UF"},
    "preview": ["xine1", "xine2"],
    "url": "",
    "mirrors": {"vk":"https://vk.com/doc-148424355_446681979", "ru":"Xin/Xin edges.xls", "yd":"https://yadi.sk/d/JA-HcD833JzMBh"},
  },
  {
    "author": "Xin Shi",
    "authorSs": "",
    "elements": {"w":"UBl"},
    "preview": ["xinw1", "xinw2"],
    "url": "",
    "mirrors": {"vk":"https://vk.com/doc-148424355_446681985", "ru":"Xin/xin wings.xls", "yd":"https://yadi.sk/d/JA-HcD833JzMBh"},
  },
  {
    "author": "Xin Shi",
    "authorSs": "",
    "elements": {"x":"Ubl"},
    "preview": ["xinx1", "xinx2"],
    "url": "",
    "mirrors": {"vk":"https://vk.com/doc-148424355_446681993", "ru":"Xin/xin x.xls", "yd":"https://yadi.sk/d/JA-HcD833JzMBh"},
  },
  {
    "author": "Jackster",
    "authorSs": "Jackster",
    "elements": {"c":"UBL"},
    "preview": ["jackster1", "jackster2"],
    "url": "https://www.speedsolving.com/forum/threads/corner-commutators-for-ulb-buffer.53628/",
    "mirrors": {"vk":"https://vk.com/doc-148424355_446681623", "ru":"jackster.txt", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"},
  },
  {
    "author": "Hari Anirudh",
    "authorSs": "hari",
    "elements": {"c":"UBL"},
    "preview": ["hari1"],
    "url": "",
    "mirrors": {"vk":"https://vk.com/doc-148424355_446681617", "ru":"Hari ULB corners.xlsx", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"}
  },
  {
    "author": "Kevin Matthews",
    "authorSs": "Keroma12",
    "elements": {"c":"UBR,UFR", "e": "UF", "x": "UFr"},
    "preview": ["keroma0", "keroma1", "keroma2"],
    "url": "https://docs.google.com/spreadsheets/d/1Ml7Jl5Yeb9HeE14xO7j1Nc99sw08oiBjLbi_nYJk9rU/",
    "mirrors": {"vk":"https://vk.com/doc-148424355_467379696", "ru":"Kevin Matthews comms.xlsx", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"}
  },
  {
    "author": "Jack Cai",
    "authorSs": "",
    "elements": {"c":"URF", "e":"UF, UB"},
    "preview": ["jack0", "jack1", "jack2"],
    "url": "https://docs.google.com/spreadsheets/d/1yl5Xwn2aDpXyHA0Rx1OUrDzec8nbg18wxis3I4uDoIw/edit",
    "mirrors": {"vk":"https://vk.com/doc-148424355_485537898", "ru":"Jacks_Comms.xlsx", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"}
  },
  {
    "author": "Jaycee",
    "authorSs": "Jaycee",
    "elements": {"c":"UBL"},
    "preview": ["jaycee1"],
    "url": "",
    "mirrors": {"vk":"https://vk.com/doc-148424355_446681634", "ru":"Jaycee UBL corners.xlsx", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"}
  },
  {
    "author": "Oleg Gritsenko",
    "authorSs": "drkorbin",
    "elements": {"5cycles e":"UF"},
    "preview": ["5cycles1", "5cycles2"],
    "url": "https://docs.google.com/spreadsheets/d/1-eWzUwiolba5IUf5fg3IYZG4DXKKFJZmD2lqsXmYrX8",
    "mirrors": {"vk":"https://vk.com/doc-148424355_446682269", "ru":"Oleg MU 5-cycles.xlsx", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"}
  },
  {
    "author": "Timo Norrkniivilä",
    "authorSs": "T1_M0",
    "elements": {"e":"FU", "x":"Ubr", "c":"UBL", "w":"FUr"},
    "preview": ["timo0","timo1","timo2"],
    "url": "https://docs.google.com/spreadsheets/d/1xR2RKxXqxpYKyqbG1Y63EpIOPlNKn1yT2QI5IWMgdYE",
    "mirrors": {"vk":"https://vk.com/doc-148424355_482521857", "ru":"Timos_bld.xlsx", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"},
  },
  {
    "author": "Bernhard Brodowsky",
    "authorSs": "Lykos",
    "elements": {"2-twists c": "all"},
    "preview": ["brod1", "brod2"],
    "url": "https://docs.google.com/spreadsheets/d/1De8iFOYe-M104gVDgtZ7kpQ_2Juq5SKC_xIsTI41SM0/edit?fbclid=IwAR3sZrbVUKxpVHcF9p7-M_oaoSHTWizq6GkXA9gMcUuylChCbak-qahEpRM#gid=1994144303",
    "mirrors": {}
  },
  {
    "author": "Heejun Kim",
    "authorSs": "CarterK",
    "elements": {"e": "UF", "c": "UFR"},
    "preview": ["carter0", "carter1"],
    "url": "https://docs.google.com/spreadsheets/d/16LH5GCl9I6sRNPMmAYEcX5M6xSkDwMa0fh35cDiwvCE/edit#gid=419448494",
    "mirrors": {"vk":"https://vk.com/doc-148424355_602082380", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"}
  },
  {
    "author": "Abhijeet Ghodgaonkar",
    "authorSs": "abunickabhi",
    "elements": {"5cycles e": "UF"},
    "preview": ["yo0", "yo1"],
    "url": "https://docs.google.com/spreadsheets/d/1brQR4RWFpNCWgi8J67nxAa-9TkAMtj5IpA_Xge_JWY8/edit?usp=sharing",
    "mirrors": {}
  },
  {
    "author": "Adrian Dębski",
    "authorSs": "AdrianD",
    "elements": {"w": "UFr", "x": "Ubl"},
    "preview": ["adrian0", "adrian1"],
    "url": "https://docs.google.com/spreadsheets/d/1CYzNgzhuE3l562pCaGXHQ3rMsDihxCiwEsHioOYSQY4",
    "mirrors": {"ru":"Adrian.xlsx", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"}
  },
  {
    "author": "CarterK",
    "authorSs": "CarterK",
    "elements": {"e": "DF", "c": "UBL"},
    "preview": ["carter0", "carter1"],
    "url": "https://docs.google.com/spreadsheets/d/1Wm7zlhpB_PP-HO5SNGbipry9TLM-jKgEh3_fkdRZHeo",
    "mirrors": {"vk":"https://vk.com/doc-148424355_452826354", "ru":"Carter Comm List.xlsx", "yd":"https://disk.yandex.ru/d/nsz48UwqDbfjBQ"}
  },
];

// using 'rank' for stable sort - initial elements position comparison in compare function
for (var i = 0; i < window.tables.length; i++) {
    window.tables[i]["rank"] = i;
}

// bestsiteeva mirrors
for (var i = 0; i < window.tables.length; i++) {
    //window.tables[i]["mirrors"]["ru"] = "http://bestsiteever.net/tables/mirrors/" + encodeURIComponent(window.tables[i]["mirrors"]["ru"]);
    if (window.tables[i]["mirrors"]["ru"] != null)
        window.tables[i]["mirrors"]["ru"] = "http://bestsiteever.net/tables/mirrors/" + window.tables[i]["mirrors"]["ru"];
}
